#! /usr/bin/python

import io
import sys
import csv
import urllib.request

COUNTRIES_PAGE = "https://raw.githubusercontent.com/mgp25/WhatsAPI-Official/master/src/countries.csv"


if len(sys.argv) > 1:
    file = open(sys.argv[1])
else:
    file = io.TextIOWrapper(urllib.request.urlopen(COUNTRIES_PAGE))

csvreader = csv.reader(file, skipinitialspace=True)

print((
    "#ifndef __WHATS_ACPPI_COUNTRIES_H__\n"
    "#define __WHATS_ACPPI_COUNTRIES_H__\n"
    "// File autogenerated, do not edit it!\n"
    "typedef struct CountryData {\n"
    "\tconst char *country;\n"
    "\tconst char *cc;\n"
    "\tconst char *mcc;\n"
    "\tconst char *iso3166;\n"
    "\tconst char *iso639;\n"
    "\tconst char *mnc;\n"
    "} CountryData;\n"
    "static CountryData COUNTRIES_DATA[] = {"
))

for row in csvreader:
    print((
        "\t{"
        "\""+row[0]+"\","
        "\""+row[1]+"\","
        "\""+row[2].split("|")[0]+"\","
        "\""+row[3]+"\","
        "\""+row[4]+"\","
        "\""+row[5]+"\""
        "},"
    ))

print("\t{NULL, NULL, NULL, NULL, NULL, NULL}")
print("};")
print("#endif")
