#! /usr/bin/python

import io
import sys
import csv
import urllib.request

NETWORKINFO_PAGE = "https://raw.githubusercontent.com/mgp25/WhatsAPI-Official/master/src/networkinfo.csv"

if len(sys.argv) > 1:
    file = open(sys.argv[1])
else:
    file = io.TextIOWrapper(urllib.request.urlopen(NETWORKINFO_PAGE))

csvreader = csv.reader(file, skipinitialspace=True)

print((
    "#ifndef __WHATS_ACPPI_NETWORKINFO_H__\n"
    "#define __WHATS_ACPPI_NETWORKINFO_H__\n"
    "// File autogenerated, do not edit it!\n"
    "typedef struct NetworkInfo {\n"
    "\tconst char *mnc;\n"
    "\tconst char *iso3166;\n"
    "\tconst char *carrierName;\n"
    "} NetworkInfo;\n"
    "static NetworkInfo NETWORK_INFO[] = {"
))

for row in csvreader:
    print((
        "\t{"
        "\""+row[2]+"\","
        "\""+row[4]+"\","
        "\""+row[7]+"\""
        "},"
    ))

print("\t{NULL, NULL, NULL}")
print("};")
print("#endif")
