#! /usr/bin/python

import io
import sys
import csv
import urllib.request

NETWORKINFO_PAGE = "https://raw.githubusercontent.com/mgp25/WhatsAPI-Official/master/src/networkinfo.csv"

if len(sys.argv) > 1:
    file = open(sys.argv[1])
else:
    file = io.TextIOWrapper(urllib.request.urlopen(NETWORKINFO_PAGE))

csvreader = csv.reader(file, skipinitialspace=True)

print((
    "#ifndef __WHATS_ACPPI_COUNTRIES_H__\n"
    "#define __WHATS_ACPPI_COUNTRIES_H__\n"
    "// File autogenerated, do not edit it!\n"
    "typedef struct CountryData {\n"
    "\tchar *country;\n"
    "\tchar *cc;\n"
    "\tchar *mcc\n"
    "\tchar *iso3166\n"
    "\tchar *iso639\n"
    "\tchar *mnc\n"
    "} CountryData;\n"
    "static CountryData COUNTRIES_DATA[] = {"
))

for row in csvreader:
    print((
        "\t{"
        "\""+row[0]+"\","
        "\""+row[1]+"\","
        "\""+row[2].split("|")[0]+"\","
        "\""+row[3]+"\","
        "\""+row[4]+"\","
        "\""+row[5]+"\""
        "},"
    ))

print("\t{NULL, 0, 0, NULL, NULL, NULL}")
print("};")
print("#endif")
